input_dump_path: /home6/fujii/master/data/deform/a6-cis-a6/360K/24mer512chain/u/z/wi_10.0.1/dump.s.lammpstrj
input_rotationtxt_path: /home6/fujii/master/data/deform/a6-cis-a6/360K/24mer512chain/u/z/wi_10.0.1/rotation.txt
output_cry_dump_path: sample_data/cry_dump.lammpstrj
output_cry_text_path: sample_data/cry.txt
k: 16
beta: 2
lambda_threshold: 0.9
neighbor_stem_distance_threshold: 8
theta_deg_threshold: 5
N: 49
M: 512
