input_dump_path: sample_data/sample.lammpstrj
output_path: sample_data/rouse_mode-p_autocorr.txt
beads_per_chain: 49
num_chain: 512
dt_fs: 5
max_frames_to_average: 500
  #total_frames_dump: 10451
total_frames_dump: 50
mode-p: 5
