input_dump_path: sample_data/erate_0.1_dt_5.u.lammpstrj
input_rotationtxt_path: sample_data/rotation.txt
output_scatter_text_path: sample_data/out.scatter.txt
freq_max: 30
freq_min: -30
resolution: 101
aspect: xz
